name: Publish to crates.io

on:
  push:
    tags:
      - 'v[0-9]+.*'
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Check package version
        run: |
          CARGO_TOML_VERSION=$(grep '^version =' Cargo.toml | sed 's/.*= *"//' | sed 's/".*//')
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          if [ "$CARGO_TOML_VERSION" != "$TAG_VERSION" ]; then
            echo "Cargo.toml version ($CARGO_TOML_VERSION) does not match tag version ($TAG_VERSION)"
            exit 1
          fi

      - name: Publish to crates.io
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}